"""add_adult_to_media

Revision ID: af55228ac709
Revises: 5dbe314a6255
Create Date: 2026-04-29 11:52:04.726305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af55228ac709'
down_revision: Union[str, Sequence[str], None] = '5dbe314a6255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('media', sa.Column('adult', sa.Boolean(), server_default='false', nullable=False))
    op.execute(
        "UPDATE media SET adult = true "
        "WHERE tmdb_data IS NOT NULL AND (tmdb_data->>'adult')::boolean = true"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'adult')
    # ### end Alembic commands ###
